import unittest
from selenium import webdriver
import requests

class test(unittest.TestCase):

    def setUp(self):
        print("Note that user should be a publisher of community that you select.")
        self.user = raw_input("Enter username: ")
        self.pwd = raw_input("Enter password: ")
        print("Note that this community should have an article in publishable state.")
        self.community_id = raw_input("Enter a community id: ")
        self.article_id = raw_input("Enter article id that belongs to above community: ")
        self.url_basic = "http://localhost:8000/"
        self.EVENT_API_TOKEN = 'e1eebb20fd4f01d6f733cc6d355b45e9fb1ed78d' #This should be generated by tester


    def test_article_published(self):
        url_api = self.url_basic + 'logapi/event/article/published/'
        headers={'Authorization': 'Token ' + str(self.EVENT_API_TOKEN)}
        result = requests.get(url_api, headers = headers).json()
        new_result={}
        for key,value in result.iteritems():
            new_result[key.lower()] = value
        if(new_result["status code"] == 200):
            data = new_result["result"]
            total_hits = new_result["total hits"]
        driver = webdriver.Firefox()
        driver.maximize_window()  # For maximizing window
        driver.get(self.url_basic)
        driver.find_element_by_xpath('//a [@href="/login/?next=/"]').click()
        driver.get(self.url_basic + "login/?next=/")
        elem = driver.find_element_by_id("id_username")
        elem.send_keys(self.user)
        elem = driver.find_element_by_id("id_password")
        elem.send_keys(self.pwd)
        driver.find_element_by_class_name('btn-block').click()
        driver.find_element_by_xpath('//a [@href="/communities/"]').click()
        driver.find_element_by_xpath('//a [@href="/community-view/' + str(self.community_id) + '/"]').click()
        driver.find_element_by_xpath('//a [@href="/community_content/' + str(self.community_id) + '/"]').click()
        driver.find_element_by_xpath('//a [@href="/community_content/' + str(self.community_id) + '/"]').click()
        driver.find_element_by_xpath('//a [@href="/article-view/' + str(self.article_id) + '/"]').click()
        driver.find_element_by_xpath('//a [@href="/article-edit/' + str(self.article_id) + '/"]').click()
        driver.find_element_by_xpath("//button [@type='submit' and @value='publish']").click()
        url_api = self.url_basic + 'logapi/event/article/published/'
        headers={'Authorization': 'Token ' + str(self.EVENT_API_TOKEN)}
        result = requests.get(url_api, headers = headers).json()
        new_result={}
        for key,value in result.iteritems():
            new_result[key.lower()] = value
        if (new_result["status code"] == 200):
            data = new_result["result"]
            if (new_result["total hits"] == total_hits+ 1):
                self.assertEqual(data[0]["event_name"], "event.article.published")
                self.assertEqual(data[0]["event"]["article-id"], self.article_id)
            else:
                self.assertFalse(True)

        driver.quit()


if __name__ == '__main__':
    unittest.main()
