import unittest
from selenium import webdriver
import requests
from decouple import config

class test(unittest.TestCase):
	
	def setUp(self):
		self.user = config("EVENT_LOGS_USER")
		self.pwd = config("EVENT_LOGS_PASSWORD")
		self.url_basic = "http://" + config("IP_ADDRESS") + ":" + config("EVENT_LOGS_PORT") + "/"
		self.token = config("EVENT_API_TOKEN")  #This should be generated by tester
		self.headers={'Authorization': 'Token ' + str(self.token)}
		self.comm_name = raw_input("Enter name of community: ")
		self.comm_tag = raw_input("Enter a tag line to community: ")
		self.comm_category = raw_input("Enter category of your community: ")
		self.comm_username = raw_input("Enter username of community creator: ")
		self.comm_image = raw_input("Enter path to community image: ")

	def test_community_create(self):
		url_api = self.url_basic + 'logapi/event/community/create/'

		result = requests.get(url_api, headers = self.headers).json()
		new_result={}
		for key,value in result.iteritems():
			new_result[key.lower()] = value
		if(new_result["status code"] == 200):
			data = new_result["result"]
			total_hits = new_result["total hits"]

		driver = webdriver.Firefox()
		driver.maximize_window() #For maximizing window
		driver.get(self.url_basic)
		driver.find_element_by_xpath('//a [@href="/login/?next=/"]').click()
		driver.get(self.url_basic + "login/?next=/")
		elem = driver.find_element_by_id("id_username")
		elem.send_keys(self.user)
		elem = driver.find_element_by_id("id_password")
		elem.send_keys(self.pwd)
		driver.find_element_by_class_name('btn-block').click()
	
		driver.get(self.url_basic+"create_community/")
		elem = driver.find_element_by_id("name")
		elem.send_keys(self.comm_name)

		elem = driver.find_element_by_id("tag_line")
		elem.send_keys(self.comm_tag)

		elem = driver.find_element_by_id("category")
		elem.send_keys(self.comm_category)

		elem = driver.find_element_by_id("username")
		elem.send_keys(self.comm_username)

		elem = driver.find_element_by_id("community_image")
		elem.send_keys(self.comm_image)

		driver.find_element_by_id("create").click()
		
		url_api = self.url_basic + 'logapi/event/community/create/'
		result = requests.get(url_api, headers = self.headers).json()
		new_result={}
		for key,value in result.iteritems():
			new_result[key.lower()] = value

		if (new_result["status code"] == 200):
			data = new_result["result"]
			if (new_result["total hits"]== total_hits+1):
				self.assertEqual(data[0]["event_name"],"event.community.create")
				self.assertEqual(data[0]["event"]["community-name"], self.comm_name)
				self.assertEqual(data[0]["event"]["admin-username"], self.comm_username)
			else:
				self.assertFalse(True)

		driver.quit()

if __name__ == '__main__':
	unittest.main()
