import unittest
from selenium import webdriver
import requests
from selenium.webdriver.support.ui import Select
from decouple import config

class test(unittest.TestCase):
	
	def setUp(self):
		self.user = config("EVENT_LOGS_USER")
		self.pwd = config("EVENT_LOGS_PASSWORD")
		self.url_basic = "http://" + config("IP_ADDRESS") + ":" + config("EVENT_LOGS_PORT") + "/"
		self.token = config("EVENT_API_TOKEN")  #This should be generated by tester
		self.headers={'Authorization': 'Token ' + str(self.token)}
		self.comm_id = raw_input("Enter Community id: ")
		#"we will create a course and then add a yutube link to it"
		self.course_id = raw_input("Enter course id: ")
		self.topic_name = raw_input("Enter topic name: ")
		self.youtube_url=raw_input("Enter a youtube url: ")

	def test_course_manage(self):
		url_api = self.url_basic + 'logapi/event/course/manage/'
		result = requests.get(url_api, headers = headers).json()
		new_result={}
		for key,value in result.iteritems():
			new_result[key.lower()] = value
		if(new_result["status code"] == 200):
			data = new_result["result"]
			total_hits = new_result["total hits"]

		driver = webdriver.Firefox()
		driver.maximize_window() #For maximizing window
		driver.implicitly_wait(20) #gives an implicit wait for 20 seconds
		driver.get(self.url_basic)
		driver.find_element_by_xpath('//a [@href="/login/?next=/"]').click()
		elem = driver.find_element_by_id("id_username")
		elem.send_keys(self.user)
		elem = driver.find_element_by_id("id_password")
		elem.send_keys(self.pwd)
		driver.find_element_by_class_name('btn-block').click()
		driver.find_element_by_xpath('//a [@href="/communities/"]').click()
		driver.find_element_by_xpath('//a [@href="/community-view/'+ self.comm_id +'/"]').click()
		driver.find_element_by_xpath('//a [@href="/community_content/'+ self.comm_id +'/"]').click()
		driver.find_element_by_xpath('//a [@href="/course-view/'+ self.course_id +'/"]').click()

		driver.find_element_by_xpath('//a [@href="/course-edit/'+ self.course_id +'/"]').click()

		elem = driver.find_element_by_id("id_name")
		elem.send_keys(self.topic_name)

		driver.find_element_by_id("save_id").click()

		driver.find_element_by_xpath('//a [@href="/manage-resource/'+ self.course_id +'/"]').click()
		select = Select(driver.find_element_by_id('topic'))
		select.select_by_visible_text(self.topic_name)
		driver.find_element_by_id("topic_type1").click()
		elem = driver.find_element_by_id("topic_link")
		elem.send_keys(self.youtube_url)
		driver.find_element_by_id("submit1").click()

		url_api = self.url_basic + 'logapi/event/course/manage/'
		result = requests.get(url_api, headers = headers).json()
		new_result={}
		for key,value in result.iteritems():
			new_result[key.lower()] = value

		if (new_result["status code"] == 200):
			data = new_result["result"]
			if (new_result["total hits"]== total_hits+1):
				self.assertEqual(data[0]["event_name"],"event.course.manage")
				self.assertEqual(data[0]["event"]["user-id"], int(self.user_id))

		driver.quit()

if __name__ == '__main__':
	unittest.main()
