import unittest
from selenium import webdriver
import requests

class test(unittest.TestCase):
	
	def setUp(self):
		self.user = raw_input("Enter username: ")
		self.pwd = raw_input("Enter password: ")
		self.community_id = raw_input("Enter a community id: ")
		self.username = raw_input("Enter a username which is part of this community: ")
		self.url_basic = "http://localhost:8000/"
		self.EVENT_API_TOKEN = 'e1eebb20fd4f01d6f733cc6d355b45e9fb1ed78d' #This should be generated by tester

	def test_event_profile_view(self):
		url_api = self.url_basic + "logapi/event/profile/view/"
		headers={'Authorization': 'Token ' + str(self.EVENT_API_TOKEN)}
		result = requests.get(url_api, headers = headers).json()
		new_result={}
		for key,value in result.iteritems():
			new_result[key.lower()] = value
		if(new_result["status code"] == 200):
			data = new_result["result"]
			total_hits = new_result["total hits"]

		driver = webdriver.Firefox()
		driver.maximize_window() #For maximizing window
		driver.implicitly_wait(20) #gives an implicit wait for 20 seconds
		driver.get("http://localhost:8000/")
		driver.find_element_by_xpath('//a [@href="/login/?next=/"]').click()
		elem = driver.find_element_by_id("id_username")
		elem.send_keys(self.user)
		elem = driver.find_element_by_id("id_password")
		elem.send_keys(self.pwd)
		driver.find_element_by_class_name('btn-block').click()
		driver.find_element_by_xpath('//a [@href="/communities/"]').click()
		driver.find_element_by_xpath('//a [@href="/community-view/' + self.community_id + '/"]').click()
		driver.find_element_by_xpath('//a [@href="/userprofile/' + self.username + '/"]').click()

		url_api = self.url_basic + 'logapi/event/profile/view/'
		headers={'Authorization': 'Token ' + str(self.EVENT_API_TOKEN)}
		result = requests.get(url_api, headers = headers).json()

		new_result={}
		for key,value in result.iteritems():
			new_result[key.lower()] = value

		if (new_result["status code"] == 200):
			data = new_result["result"]
			if (new_result["total hits"]== total_hits+1):
				self.assertEqual(data[0]["event_name"],"event.profile.view")
				self.assertEqual(data[0]["event"]["user-visited"], self.username)


if __name__ == '__main__':
	unittest.main()